services:
  user_service:
    build: ./services/user_service
    container_name: user_service
    ports:
      - "8001:8001"
    networks:
      - microservices
    environment:
      - JAEGER_HOST=jaeger
    depends_on:
      - user_db
      - jaeger

  order_service:
    build: ./services/order_service
    container_name: order_service
    ports:
      - "8002:8002"
    networks:
      - microservices
    environment:
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    depends_on:
      - order_db
      - zipkin

  payment_service:
    build: ./services/payment_service
    container_name: payment_service
    ports:
      - "8003:8003"
    networks:
      - microservices
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    depends_on:
      - payment_db
      - jaeger

  user_db:
    image: postgres:13
    container_name: user_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    volumes:
      - user_data:/var/lib/postgresql/data
      - ./services/user_service/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - microservices

  order_db:
    image: postgres:13
    container_name: order_db
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orderdb
    volumes:
      - order_data:/var/lib/postgresql/data
      - ./services/order_service/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - microservices

  payment_db:
    image: postgres:13
    container_name: payment_db
    environment:
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: paymentdb
    volumes:
      - payment_data:/var/lib/postgresql/data
      - ./services/payment_service/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - microservices

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - microservices

  jaeger:
    image: jaegertracing/all-in-one:1.39
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9412
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - microservices

networks:
  microservices:
    driver: bridge

volumes:
  user_data:
  order_data:
  payment_data: